name = "autoformalizer"
version = "0.1.0"
defaultTargets = ["Autoformalizer"]

[[lean_lib]]
name = "Autoformalizer"

[[lean_exe]]
name = "autoformalizer"
root = "Autoformalizer.CLI.Main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.12.0"
