retry:
  max_attempts: 5
  beam_schedule: [1, 3, 3, 5, 5]
  temperature_schedule: [0.3, 0.5, 0.5, 0.7, 0.8]
  max_tokens: 512

executor:
  use_cache: true

cli:
  compile_check: true
  compilation_timeout: 30.0
  output_dir: "."
  train_ratio: 0.6
  dev_ratio: 0.2
  test_ratio: 0.2
  seed: 42
  show_items: 0
  eval_dataset: "datasets/test.jsonl"
  pass_k: [1, 5]
  default_model: "x-ai/grok-4-fast"
