name: Static Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-type-format:
    name: Lint, Format, Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v1
        with:
          python-version: "3.11"
          uv-version: "0.4.0"

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Check formatting
        run: make format-check

      - name: Lint
        run: make lint

      - name: Type check
        run: make type-check
